### ISSUE TITLE
Add a link to help documentation.

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/student-dashboard-django#182]
Add a link to the dashboard pages to the Google help documentation:

https://docs.google.com/document/d/1Av0SJQGsMf-EmChLpygUi5-a603w6D6zROT7p48mwkI/edit?usp=sharing

**Comment by jennlove-um** [comment]
From the home page, link to the first page of the help doc: https://docs.google.com/document/d/1Av0SJQGsMf-EmChLpygUi5-a603w6D6zROT7p48mwkI/edit?usp=sharing

From the What Students Are Reading page, link to that section in the help: https://docs.google.com/document/d/1Av0SJQGsMf-EmChLpygUi5-a603w6D6zROT7p48mwkI/edit#heading=h.ei0djpnrbuw

From the Assignments Planning Tool, link to that section in the help: https://docs.google.com/document/d/1Av0SJQGsMf-EmChLpygUi5-a603w6D6zROT7p48mwkI/edit#bookmark=id.j326p1brruc1

From the Grade Distribution page, link to that section in the help: https://docs.google.com/document/d/1Av0SJQGsMf-EmChLpygUi5-a603w6D6zROT7p48mwkI/edit#bookmark=id.9qq8fcgci5m7

**Comment by jonespm** [comment]
I'm not sure if we need context sensitive help currently. I also wouldn't want these help documents to be links to Google documents.

Minimally the documents we link should be published documents (File->Publish to the Web)
I think it would be better if all of these were on a Google Sites (sites.google.com) and organized together there rather than individual files here. 

If you created a new "Google Site" and had these pages with these titles and URL's on them it would be nicer.

**Comment by jennlove-um** [comment]
Is this more like what you're thinking with a Google site?  https://sites.google.com/umich.edu/student-dashboard-help/home

**Comment by jonespm** [comment]
1000% yes! ;)

**Comment by pushyamig** [comment]
Done
