### ISSUE TITLE
Change table/column name in Mysql with lower case 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/student-dashboard-django#29]
Django MySQL notes advise against using mixed case or upper case table names due to a known bug in MySQL.
https://docs.djangoproject.com/en/2.1/ref/databases/#table-names

**Comment by jonespm** [comment]
Are you working on this one @pushyamig ? This seems like it would be nice to have sooner rather than later. (Though we could run a conversion)

**Comment by pushyamig** [comment]
I am not currently working, I opened as an issue for awareness/ should work pilot. If you like to work on it  go ahead

**Comment by jonespm** [comment]
We really should be lowercase for everything, table names and column names. Otherwise it can cause problems depending on the OS and lots of confusion in the code. In our current database some columns are upper case some are lower case.

https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

**Comment by jonespm** [comment]
Also, we're running
python manage.py migrate

But we're also putting a script in the docker startup location. We should just switch to django migrations similar to student explorer going forward? 

https://github.com/tl-its-umich-edu/student_explorer/tree/develop/management/migrations

Maybe a separate issue.

**Comment by pushyamig** [comment]
Done
